In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\deshp\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\deshp\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\deshp\anaconda3\lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\deshp\anaconda3\lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\deshp\anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io_loop.start()
  File "C:\Users\deshp\anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\deshp\anaconda3\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "C:\Users\deshp\anaconda3\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "C:\Users\deshp\anaconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\deshp\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "C:\Users\deshp\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "C:\Users\deshp\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 437, in dispatch_shell
    await result
  File "C:\Users\deshp\anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "C:\Users\deshp\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "C:\Users\deshp\anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "C:\Users\deshp\anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\deshp\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3024, in run_cell
    result = self._run_cell(
  File "C:\Users\deshp\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3079, in _run_cell
    result = runner(coro)
  File "C:\Users\deshp\anaconda3\lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\deshp\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3284, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\deshp\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3466, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\deshp\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\deshp\AppData\Local\Temp\ipykernel_30476\3538350959.py", line 1, in <module>
    import pandas as pd
  File "C:\Users\deshp\anaconda3\lib\site-packages\pandas\__init__.py", line 26, in <module>
    from pandas.compat import (
  File "C:\Users\deshp\anaconda3\lib\site-packages\pandas\compat\__init__.py", line 27, in <module>
    from pandas.compat.pyarrow import (
  File "C:\Users\deshp\anaconda3\lib\site-packages\pandas\compat\pyarrow.py", line 8, in <module>
    import pyarrow as pa
  File "C:\Users\deshp\anaconda3\lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\deshp\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\deshp\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\deshp\anaconda3\lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\deshp\anaconda3\lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\deshp\anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io_loop.start()
  File "C:\Users\deshp\anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\deshp\anaconda3\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "C:\Users\deshp\anaconda3\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "C:\Users\deshp\anaconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\deshp\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "C:\Users\deshp\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "C:\Users\deshp\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 437, in dispatch_shell
    await result
  File "C:\Users\deshp\anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "C:\Users\deshp\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "C:\Users\deshp\anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "C:\Users\deshp\anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\deshp\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3024, in run_cell
    result = self._run_cell(
  File "C:\Users\deshp\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3079, in _run_cell
    result = runner(coro)
  File "C:\Users\deshp\anaconda3\lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\deshp\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3284, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\deshp\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3466, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\deshp\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\deshp\AppData\Local\Temp\ipykernel_30476\3538350959.py", line 1, in <module>
    import pandas as pd
  File "C:\Users\deshp\anaconda3\lib\site-packages\pandas\__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "C:\Users\deshp\anaconda3\lib\site-packages\pandas\core\api.py", line 9, in <module>
    from pandas.core.dtypes.dtypes import (
  File "C:\Users\deshp\anaconda3\lib\site-packages\pandas\core\dtypes\dtypes.py", line 24, in <module>
    from pandas._libs import (
  File "C:\Users\deshp\anaconda3\lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

In [2]:
df = pd.read_csv(r"C:\Users\deshp\Downloads\archive (2)\Mental Health Dataset.csv")

In [3]:

total_rows=len(df)
percent_data=int(total_rows* 0.1)
df=df.iloc[:percent_data]

In [4]:
len(df)

29236

In [5]:
df.drop(columns=['Days_Indoors', 'Work_Interest', 'Timestamp', 'self_employed'], inplace=True)

In [6]:
df

,Gender,Country,Occupation,family_history,treatment,Growing_Stress,Changes_Habits,Mental_Health_History,Mood_Swings,Coping_Struggles,Social_Weakness,mental_health_interview,care_options
0,Female,United States,Corporate,No,Yes,Yes,No,Yes,Medium,No,Yes,No,Not sure
1,Female,United States,Corporate,Yes,Yes,Yes,No,Yes,Medium,No,Yes,No,No
2,Female,United States,Corporate,Yes,Yes,Yes,No,Yes,Medium,No,Yes,No,Yes
3,Female,United States,Corporate,Yes,Yes,Yes,No,Yes,Medium,No,Yes,Maybe,Yes
4,Female,United States,Corporate,Yes,Yes,Yes,No,Yes,Medium,No,Yes,No,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...
29231,Female,United States,Student,Yes,Yes,Maybe,Yes,Yes,Low,Yes,Maybe,No,No
29232,Female,United States,Student,Yes,Yes,Maybe,Yes,Yes,Low,Yes,Maybe,No,Yes
29233,Female,United States,Student,No,Yes,Maybe,Yes,Yes,Low,Yes,Maybe,No,Not sure
29234,Female,United States,Student,Yes,Yes,Maybe,Yes,Yes,Low,Yes,Maybe,No,Yes
29235,Female,United States,Student,No,No,Maybe,Yes,Yes,Low,Yes,Maybe,No,Not sure

In [7]:
df['Changes_Habits'].replace('Maybe', 'Yes', inplace=True)

C:\Users\deshp\AppData\Local\Temp\ipykernel_30476\3232139187.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Changes_Habits'].replace('Maybe', 'Yes', inplace=True)

In [8]:
df['Social_Weakness'] = df['Social_Weakness'].replace({'Yes': 1, 'No': 0, 'Maybe': 1})

C:\Users\deshp\AppData\Local\Temp\ipykernel_30476\1772910149.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Social_Weakness'] = df['Social_Weakness'].replace({'Yes': 1, 'No': 0, 'Maybe': 1})

In [9]:
df['mental_health_interview'].replace('Maybe', 'No', inplace=True)

C:\Users\deshp\AppData\Local\Temp\ipykernel_30476\2123923361.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['mental_health_interview'].replace('Maybe', 'No', inplace=True)

In [10]:
df['care_options'] = df['care_options'].replace({'Yes': 1, 'No': 0, 'Not sure':0})

C:\Users\deshp\AppData\Local\Temp\ipykernel_30476\3477085263.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['care_options'] = df['care_options'].replace({'Yes': 1, 'No': 0, 'Not sure':0})

In [11]:

df['Growing_Stress'] = df['Growing_Stress'].replace({'Yes': 1, 'No': 0, 'Maybe': 0})

C:\Users\deshp\AppData\Local\Temp\ipykernel_30476\2592429668.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Growing_Stress'] = df['Growing_Stress'].replace({'Yes': 1, 'No': 0, 'Maybe': 0})

In [12]:
X = df.iloc[:, 0:13].drop(columns='treatment')

In [14]:
df['Occupation']

0        Corporate
1        Corporate
2        Corporate
3        Corporate
4        Corporate
           ...
29231      Student
29232      Student
29233      Student
29234      Student
29235      Student
Name: Occupation, Length: 29236, dtype: object

In [15]:
from sklearn import preprocessing

# Initialize LabelEncoder
label_encoder = preprocessing.LabelEncoder()
df['treatment']= label_encoder.fit_transform(df['treatment'])

In [16]:
y = df['treatment']

In [20]:
y

0        1
1        1
2        1
3        1
4        1
        ..
29231    1
29232    1
29233    1
29234    1
29235    0
Name: treatment, Length: 29236, dtype: int64

In [27]:
X

,Gender,Country,Occupation,family_history,Growing_Stress,Changes_Habits,Mental_Health_History,Mood_Swings,Coping_Struggles,Social_Weakness,mental_health_interview,care_options
0,Female,United States,Corporate,No,1,No,Yes,Medium,No,1,No,0
1,Female,United States,Corporate,Yes,1,No,Yes,Medium,No,1,No,0
2,Female,United States,Corporate,Yes,1,No,Yes,Medium,No,1,No,1
3,Female,United States,Corporate,Yes,1,No,Yes,Medium,No,1,No,1
4,Female,United States,Corporate,Yes,1,No,Yes,Medium,No,1,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...
29231,Female,United States,Student,Yes,0,Yes,Yes,Low,Yes,1,No,0
29232,Female,United States,Student,Yes,0,Yes,Yes,Low,Yes,1,No,1
29233,Female,United States,Student,No,0,Yes,Yes,Low,Yes,1,No,0
29234,Female,United States,Student,Yes,0,Yes,Yes,Low,Yes,1,No,1
29235,Female,United States,Student,No,0,Yes,Yes,Low,Yes,1,No,0

In [31]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Define the categorical columns directly
categorical_columns = ['Gender', 'Country', 'Occupation', 'family_history', 'Changes_Habits', 
                       'Mental_Health_History', 'Mood_Swings', 'Coping_Struggles', 'mental_health_interview']

# Create the ColumnTransformer with OneHotEncoder for categorical columns
ct = ColumnTransformer(
    transformers=[('encoder', OneHotEncoder(), categorical_columns)],  # Apply encoder to categorical columns
    remainder='passthrough'  # Keep other columns as they are (i.e., numerical columns will remain unchanged)
)

# Apply transformation to X
X= np.array(ct.fit_transform(X))  # X is your original DataFrame

In [32]:
X

array([[1., 0., 0., ..., 1., 1., 0.],
       [1., 0., 0., ..., 1., 1., 0.],
       [1., 0., 0., ..., 1., 1., 1.],
       ...,
       [1., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 1., 1.],
       [1., 0., 0., ..., 0., 1., 0.]])

In [33]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [39]:

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
# Initialize RandomForestClassifier
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)

# Fit the classifier to the training data
rf_classifier.fit(X_train, y_train)

# Make predictions
y_pred = rf_classifier.predict(X_test)

# Calculate accuracy and classification report
accuracy = accuracy_score(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

# Print the results
print(f"Accuracy: {accuracy:.2f}")
print("\nClassification Report:\n", classification_rep)

Accuracy: 0.73

Classification Report:
               precision    recall  f1-score   support

           0       0.56      0.50      0.53      1752
           1       0.79      0.83      0.81      4096

    accuracy                           0.73      5848
   macro avg       0.68      0.67      0.67      5848
weighted avg       0.72      0.73      0.73      5848

In [51]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

model = RandomForestClassifier(
    n_estimators=100, 
    max_features="sqrt", 
    max_depth=6, 
    max_leaf_nodes=6
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

In [52]:
print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

           0       0.11      1.00      0.21       251
           1       1.00      0.73      0.84      7058

    accuracy                           0.73      7309
   macro avg       0.56      0.86      0.52      7309
weighted avg       0.97      0.73      0.82      7309

In [55]:
model_random = RandomForestClassifier(max_depth=3,
                                      max_features='log2',
                                      max_leaf_nodes=6,
                                      n_estimators=100)
model_random.fit(x_train, y_train)
y_pred_rand = model.predict(x_test)
print(classification_report(y_pred_rand, y_test))

              precision    recall  f1-score   support

           0       0.11      1.00      0.21       251
           1       1.00      0.73      0.84      7058

    accuracy                           0.73      7309
   macro avg       0.56      0.86      0.52      7309
weighted avg       0.97      0.73      0.82      7309